### ISSUE TITLE
layout not computed whenever original positions are 0

### ISSUE THREAD

**Issue by mef** [graphology/graphology-layout-forceatlas2#12]
Whenever forceAtlas2 layout is called on a graph where all nodes have positions initialized to `{x: 0, y: 0}`, the layout does not get computed, and the function returns `0` for all coordinates.

If the nodes positions are initialized to `{x: 1, y: 1}`, then the function returns updated coordinates, which looks to be normal.

Is this the expected behaviour?

**Comment by Yomguithereal** [comment]
Seems weird indeed. My guess is that it is an edge case that will yield null delta results for the layout computations making everything stand still. In any case it is a bad idea to start your layout with all the nodes having the same positions.

@jacomyma any insight?

**Comment by mef** [comment]
Thanks. I'll initialize the coordinates to random positions, then.

It might be worth checking whether an individual node having coordinates `(0, 0)` will be managed correctly by the layout function...

**Comment by Yomguithereal** [comment]
I think a single node with `(0, 0)` should work. But if you happen to test it, I would like to know if it breaks indeed.

**Comment by mef** [comment]
I just checked, it works as expected whenever only one node has `(0,0)` as initial coordinates.

```javascript
const {UndirectedGraph} = require('graphology')
	, FA2Layout = require('graphology-layout-forceatlas2')


var graph = new UndirectedGraph();

var data = {
  John: {
	size: 4,
	x: 0,
	y: 0
  },
  Martha: {
	x: 10,
	y: 5
  },
  Ada: {
	x: 23,
	y: -2
  }
};

for (var node in data)
  graph.addNode(node, data[node]);

graph.addEdge('John', 'Martha');
graph.addEdge('Martha', 'Ada', {weight: 3});


const positions = FA2Layout(graph, {iterations: 50});

console.log(positions)

// outputs
// [Object: null prototype] {
//   John: { x: -1.7632933855056763, y: 0.07110077142715454 },
//   Martha: { x: 0.09261119365692139, y: 0.0047854590229690075 },
//   Ada: { x: 2.2585043907165527, y: 0.06706567853689194 }
//  }

```

**Comment by Yomguithereal** [comment]
Thanks for checking this @mef.

**Comment by Yomguithereal** [comment]
I added a comment about this edge case [here](https://github.com/graphology/graphology-layout-forceatlas2#pre-requisites) @mef
