### ISSUE TITLE
How can I specify the number of iterations when using web workers?

### ISSUE THREAD

**Issue by maccman** [graphology/graphology-layout-forceatlas2#20]
The web workers don't take the `iterations` arguments.

**Comment by Yomguithereal** [comment]
Hello @maccman, the web worker rationale is to enable users to run the layout live while rendering the graph and animating the node movements using sigma.js for instance. As such it was not given a way to only run a finite number of iterations. If you need to only run a finite number of iterations, you can use the synchronous version of the algorithm, as exported by this library, and wrap the code into your own web worker if you don't want to freeze UI while performing the iterations. But I could understand you would find this cumbersome and could add some kind of helper to the worker code to help you achieve this. Can you just describe your use case a bit more so I know what would be the more relevant?

**Comment by maccman** [comment]
You've got it in one! A helper would certainly be useful, but I can figure it out.
